import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import noPhysicalDirectionClasses from "./eslint-rules/no-physical-direction-classes.mjs";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  // RTL guard: Arabic is a first-class language here, so physical-direction
  // Tailwind classes are an error, not a style preference. See AGENTS.md.
  {
    files: ["src/**/*.{ts,tsx,js,jsx}"],
    plugins: {
      wanasa: { rules: { "no-physical-direction-classes": noPhysicalDirectionClasses } },
    },
    rules: {
      "wanasa/no-physical-direction-classes": "error",
    },
  },

  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated artifacts — never lint these.
    ".open-next/**", // OpenNext build output (bundled Worker)
    ".wrangler/**", // Wrangler local state (created by `wrangler dev`)
    "cloudflare-env.d.ts", // generated by `npm run cf-typegen`
    "drizzle/migrations/**", // generated SQL migrations
  ]),
]);

export default eslintConfig;
